version: 2.1

setup: true

orbs:
  sam: circleci/aws-sam-serverless@6.1.0
  aws-cli: circleci/aws-cli@4.0.0
  terraform: circleci/terraform@3.2.1

jobs:
  deploy-serverless:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - aws-cli/install
      - sam/install
      - run:
          name: Conditionally Deploy Serverless Stack with SAM
          command: |
            if [[ -z "$CIRCLE_PULL_REQUEST" ]]; then
              echo "No PR detected – running SAM deploy..."
              sam build
              sam deploy --stack-name rds-automation-stack \
                         --capabilities CAPABILITY_IAM \
                         --capabilities CAPABILITY_NAMED_IAM \
                         --region $AWS_REGION \
                         --resolve-s3 \
                         --no-confirm-changeset \
                         --no-fail-on-empty-changeset
            else
              echo "PR detected – skipping SAM deploy."
            fi

  apply-terraform:
    executor:
      name: terraform/default
      tag: "1.5.7"
    steps:
      - checkout
      - run:
          name: Terraform Apply to PR Merged Path
          command: |
            if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
              echo "PR detected – proceeding with Terraform apply..."
              PR_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | awk -F '/' '{print $NF}')
              CHANGED_FILE=$(gh pr view "$PR_NUMBER" \
                --repo "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" \
                --json files --jq '.files[0].path')
              echo "Changed file: $CHANGED_FILE"

              TARGET_PATH=$(echo "$CHANGED_FILE" | sed -E 's|terraform/env/([^/]+).*|\1|')
              echo "TARGET_PATH=$TARGET_PATH"
              cd "terraform/env/$TARGET_PATH"

              terraform init -input=false
              terraform validate
              terraform plan -input=false -out=tfplan
              terraform show tfplan
              terraform apply -input=false -auto-approve tfplan
            else
              echo "Not a PR – skipping Terraform apply."
            fi

workflows:
  version: 2
  serverless-rds-provision:
    jobs:
      - deploy-serverless:
          filters:
            branches:
              only: main
      - apply-terraform:
          filters:
            branches:
              only: main
